# config/packages/trigger_mapping.yaml
trigger_mapping:
    storage:
        type: 'php'
        directory: '%kernel.project_dir%/src/Triggers'
        namespace: 'App\Triggers'
    migrations: true
    excludes:
        - audit_logs_trigger_we_dont_own
        - extension_xxx_trigger
